apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: startup-nextjs-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: startup-nextjs-deployment # The deployment to scale
  minReplicas: 3 # Minimum number of replicas
  maxReplicas: 10 # Maximum number of replicas
  targetCPUUtilizationPercentage: 70 # Target CPU usage percentage; pods will scale if utilization is higher than this