apiVersion: v1
kind: Service
metadata:
  name: startup-nextjs-service
spec:
  type: NodePort # Exposes the service on a port on each node in the cluster (should be replaced with LoadBalancer for cloud deployments)
  selector:
    app: startup-nextjs # Targets pods with this label
  ports:
    - port: 3000 # Port that the service will expose internally within the cluster
      targetPort: 3000 # The port that the container is listening on
      nodePort: 30000 # External port on the node to access the service from outside the cluster